Level1 = [
            [M,M,M,M,M,M,M,M,M,M,M,M,M,M,MV]
            [G,G,G,G,G,G,G,G,G,MV,G,G,G,G,MV]
            [MV,M,M,M,M,M,M,G,G,MV,G,G,M,M,MV]
            [MV,G,G,G,G,G,G,G,G,MV,G,G,M,M,MV]
            [MV,G,G,G,M,M,M,M,G,G,G,G,M,M,MV]
            [MV,M,M,M,M,M,G,G,G,M,G,G,G,G,MV]
            [MV,G,G,G,G,G,G,G,M,M,G,M,M,G,MV]
            [MV,G,M,G,G,G,M,G,G,M,G,G,M,G,MV]
            [MV,G,M,M,M,M,M,M,M,M,M,M,M,G,MV]
            [MV,G,M,G,G,G,G,G,G,M,G,G,G,G,MV]
            [MV,G,M,M,G,G,M,G,M,M,G,M,G,G,MV] 
            [MV,G,G,G,G,G,MV,G,M,M,G,M,M,M,MV] 
            [MV,G,G,G,G,G,MV,G,G,G,G,G,G,G,G]
            [M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M] 
           ]